Repository microsoft/ApplicationInsights-dotnet, pull requests merged in 2018-11, with the labels that each got.

#815 update dependencies (test libraries)
  Test/Microsoft.ApplicationInsights.Test/Net45/Microsoft.ApplicationInsights.Net45.Tests.csproj
  Test/Microsoft.ApplicationInsights.Test/Net46/Microsoft.ApplicationInsights.Net46.Tests.csproj
  Test/Microsoft.ApplicationInsights.Test/Standalone/Microsoft.ApplicationInsights.Isolated.Tests.csproj
  Test/Microsoft.ApplicationInsights.Test/netcoreapp11/Microsoft.ApplicationInsights.netcoreapp11.Tests.csproj
  Test/ServerTelemetryChannel.Test/Net45.Tests/TelemetryChannel.Net45.Tests.csproj
  Test/ServerTelemetryChannel.Test/NetCore.Tests/TelemetryChannel.netcoreapp11.Tests.csproj
  Test/ServerTelemetryChannel.Test/NetCore20.Tests/TelemetryChannel.netcoreapp20.Tests.csproj
  Test/ServerTelemetryChannel.Test/TelemetryChannel.Nuget.Tests/TelemetryChannel.Nuget.Tests.csproj
Labels: FUNdamentals

#709 Use SHA256 for checksum algorithm
  Common.props
Labels: FUNdamentals

#986 RequestTelemetry contructor modified to revert behavior change from previous PR
  Test/Microsoft.ApplicationInsights.Test/Shared/DataContracts/RequestTelemetryTest.cs
  src/Microsoft.ApplicationInsights/DataContracts/RequestTelemetry.cs
Labels: bug

#1005 Perf fix for Metric.TryGetDataSeries by avoiding string computation except when require.
  CHANGELOG.md
  src/Microsoft.ApplicationInsights/Metric.cs
Labels: performance
